language: csharp
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode11.3
branches:
  only:
  - master
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono: latest
dotnet: 3.1
script:
- ./build.sh --target "BuildAndTest" --currentBranch=$TRAVIS_BRANCH