language: csharp
dist: xenial
branches:
  only:
  - master
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono: latest
dotnet: 3.1
script:
- ./build.sh --target=BuildAndTest