trigger:
  - master

variables:
  DOTNET_SDK_VERSION: '3.1.101'

pool:
  vmImage: 'windows-2019'

steps:
  - task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(DOTNET_SDK_VERSION)'
  inputs:
      version: '$(DOTNET_SDK_VERSION)'

  - powershell: ./build.ps1 --target=BuildAndTest
  displayName: 'Execute Cake PowerShell Bootstrapper'